version: '3'

services:
  nginx:
    image: alexlionnel/fibonacci-nginx-10-14
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: nginx
    ports:
      - '80:80'
  server:
    image: alexlionnel/fibonacci-server-10-14
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: alexlionnel/fibonacci-client-10-14
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: client
  worker:
    image: alexlionnel/fibonacci-worker-10-14
    deploy:
      resources:
        limits:
          memory: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

volumes:
  db:
    driver: local