name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t alexlionnel/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true alexlionnel/react-test npm test

      - run: docker build -t alexlionnel/fibonacci-client-10-14 ./client
      - run: docker build -t alexlionnel/fibonacci-nginx-10-14 ./nginx
      - run: docker build -t alexlionnel/fibonacci-server-10-14 ./server
      - run: docker build -t alexlionnel/fibonacci-worker-10-14 ./worker

      - run: docker push alexlionnel/fibonacci-client-10-14
      - run: docker push alexlionnel/fibonacci-nginx-10-14
      - run: docker push alexlionnel/fibonacci-server-10-14
      - run: docker push alexlionnel/fibonacci-worker-10-14

